Update detect

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,4 +1,9 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-echo "Yarn Workspace Build"
-exit 0
+if [ -f $1/.buildpacks ]; then
+  echo "Yarn Workspaces Build"
+  exit 0
+else
+  echo "Missing .buildpacks file"
+  exit 1
+fi
